name: feature_first_structure
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.13
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen_runner: ^5.8.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  jwt_decoder: ^2.0.1
  loader_overlay: ^4.0.3
  loading_indicator: ^3.1.1
  shared_preferences: ^2.3.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/icons/
    - assets/logo/


flutter_gen:
  output: lib/shared/generated
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    lottie: true


